"""
Auto-generate TradingView Pine Script with embedded RS data
This script reads the CSV and generates a Pine Script file with RS data embedded as arrays
"""

import pandas as pd
import json
from datetime import datetime

def generate_pine_script(csv_path='saudiexchange_rs_analysis.csv', 
                         output_path='saudi_rs_auto_generated.pine'):
    """
    Generate Pine Script with embedded RS data from CSV
    """
    
    print("[pine-gen] Reading CSV data...")
    df = pd.read_csv(csv_path, encoding='utf-8-sig')
    
    # Sort by Symbol for consistency
    df = df.sort_values('Symbol').reset_index(drop=True)
    
    # Prepare data arrays
    symbols = df['Symbol'].tolist()
    companies = df['Company'].tolist()
    rs_values = df['RS'].tolist()
    
    # Generate arrays as Pine Script code
    symbols_array = ', '.join([f'"{s}"' for s in symbols])
    companies_array = ', '.join([f'"{c.replace('"', "'")}"' for c in companies])
    rs_array = ', '.join([str(int(r)) for r in rs_values])
    
    total_stocks = len(df)
    last_update = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    # Generate Pine Script
    pine_code = f'''//=============================================================================
// Saudi Market RS Rating - Auto-Generated
// Data Source: https://github.com/Youssef-Waheed1/lumivst_test
// Total Stocks: {total_stocks}
// Last Update: {last_update}
// 
// This script is AUTO-GENERATED by GitHub Actions
// Do NOT edit manually - changes will be overwritten
//=============================================================================

//@version=5
indicator(title='Saudi RS (Auto-Updated)', shorttitle='Saudi RS Auto', overlay=true, max_bars_back = 253)

// ===== EMBEDDED DATA (Auto-Generated) =====
// This data is automatically updated daily from CSV

var string[] SYMBOLS = array.from({symbols_array})
var string[] COMPANIES = array.from({companies_array})
var int[] RS_VALUES = array.from({rs_array})

var int TOTAL_STOCKS = {total_stocks}
var string LAST_UPDATE = "{last_update}"

// ===== CONFIGURATION =====
comparativeTickerId = 'TADAWUL:TASI'

// ===== INPUTS =====
hideRSRat   = input(false, title='Hide Rating', group = 'RS Line')
colorRS     = input(color.rgb(0, 0, 255,0), title = 'Color', group = 'RS Line')
lineTicker  = input('TADAWUL:TASI', title='Comparative Symbol', group = 'Display')
IndexValue  = input(11500, title='Approximate TASI Value', group = 'Display')
offset      = input.int(80, minval = 0, maxval = 2000, title='Offset (%)', group = 'Display')
showTable   = input(true, title='Show RS Table', group = 'Display')

// ===== FIND CURRENT STOCK RS =====
var int currentRS = na
var string currentCompany = ""
var int stockIndex = -1

// Extract symbol from current ticker (e.g., "TADAWUL:1120" → "1120")
currentSymbol = str.tostring(syminfo.ticker)

// Search for current stock in our data
for i = 0 to array.size(SYMBOLS) - 1
    if str.tostring(array.get(SYMBOLS, i)) == currentSymbol
        stockIndex := i
        currentRS := array.get(RS_VALUES, i)
        currentCompany := array.get(COMPANIES, i)
        break

// ===== RS LINE CALCULATION =====
n63  = bar_index < 63  ? bar_index : 63 
n126 = bar_index < 126 ? bar_index : 126
n189 = bar_index < 189 ? bar_index : 189
n252 = bar_index < 252 ? bar_index : 252

comparativeSymbol = request.security(lineTicker, timeframe.period, close)
rsCurve = (close/comparativeSymbol)
rsRatio = timeframe.isweekly ? IndexValue*(offset-10)/100 : IndexValue*offset/100
rs = rsCurve*rsRatio

rsPlot = plot(rs, title='RS Line', style=plot.style_line, linewidth=1, color=colorRS)

// ===== RS TABLE =====
var table rsInfoTable = table.new(position.top_right, 2, 5, 
     bgcolor = color.new(color.rgb(30, 34, 45), 10), 
     border_width = 1, 
     border_color = color.new(color.rgb(42, 46, 57), 50))

if barstate.islast and showTable and timeframe.isdaily
    // Header
    table.cell(rsInfoTable, 0, 0, "Saudi RS", text_color = color.white, 
               bgcolor = color.rgb(42, 46, 57), text_size = size.normal)
    table.cell(rsInfoTable, 1, 0, "Data", text_color = color.white, 
               bgcolor = color.rgb(42, 46, 57), text_size = size.normal)
    
    // Company
    table.cell(rsInfoTable, 0, 1, "Company", text_color = color.rgb(120, 123, 134), text_size = size.small)
    companyText = stockIndex >= 0 ? currentCompany : "N/A"
    table.cell(rsInfoTable, 1, 1, companyText, text_color = color.white, text_size = size.small)
    
    // Symbol
    table.cell(rsInfoTable, 0, 2, "Symbol", text_color = color.rgb(120, 123, 134), text_size = size.small)
    table.cell(rsInfoTable, 1, 2, currentSymbol, text_color = color.white, text_size = size.small)
    
    // RS Rating
    table.cell(rsInfoTable, 0, 3, "RS Rating", text_color = color.rgb(120, 123, 134), text_size = size.small)
    rsText = stockIndex >= 0 ? str.tostring(currentRS) : "N/A"
    rsColor = currentRS >= 80 ? color.new(color.rgb(0, 230, 119), 20) : 
              currentRS >= 50 ? color.new(color.rgb(0, 150, 255), 20) : 
              color.new(color.rgb(255, 82, 82), 20)
    table.cell(rsInfoTable, 1, 3, rsText, text_color = color.white, 
               bgcolor = stockIndex >= 0 ? rsColor : na, text_size = size.large)
    
    // Rank
    table.cell(rsInfoTable, 0, 4, "Rank", text_color = color.rgb(120, 123, 134), text_size = size.small)
    rankText = stockIndex >= 0 ? "#" + str.tostring(TOTAL_STOCKS - stockIndex) + " / " + str.tostring(TOTAL_STOCKS) : "N/A"
    table.cell(rsInfoTable, 1, 4, rankText, text_color = color.rgb(209, 212, 220), text_size = size.tiny)

// ===== DISPLAY RS LABEL =====
isDaily = timeframe.isdaily
labelText = stockIndex >= 0 ? str.tostring(currentRS) : "N/A"
labelColor = currentRS >= 80 ? color.new(color.rgb(0, 230, 119), 20) : 
             currentRS >= 50 ? color.new(color.rgb(0, 150, 255), 20) : 
             color.new(color.rgb(255, 82, 82), 20)

label1 = (hideRSRat == false) and barstate.islast and isDaily and stockIndex >= 0 ? 
         label.new(bar_index, rs, text='     RS: ' + labelText, 
                   color = labelColor, size=size.normal, 
                   textcolor=color.white, 
                   style=label.style_label_left, 
                   yloc=yloc.price) : na

// Delete previous label
label.delete(label1[1])

// Warning for non-Saudi stocks
if barstate.islast and stockIndex < 0
    label.new(bar_index, high, text='⚠️ Not a Saudi stock\\nor data not available', 
              color=color.red, style=label.style_label_down, 
              textcolor=color.white, size=size.small)

// Warning for non-daily timeframe
if (not isDaily and barstate.islast)
    label.new(bar_index + 10, high, text='⚠️ Use Daily (1D)', 
              color=color.orange, style=label.style_label_down, 
              textcolor=color.white, size=size.small)

// ===== INFO =====
// Data updated: {last_update}
// Total stocks: {total_stocks}
// GitHub: https://github.com/Youssef-Waheed1/lumivst_test
'''

    # Save to file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(pine_code)
    
    print(f"[pine-gen] Generated Pine Script: {output_path}")
    print(f"[pine-gen] Total stocks: {total_stocks}")
    print(f"[pine-gen] Last update: {last_update}")
    
    # Also generate a metadata file
    metadata = {
        'total_stocks': total_stocks,
        'last_update': last_update,
        'symbols_count': len(symbols),
        'file_size': len(pine_code),
        'generated_at': datetime.now().isoformat()
    }
    
    with open('saudi_rs_auto_metadata.json', 'w', encoding='utf-8') as f:
        json.dump(metadata, f, indent=2)
    
    print(f"[pine-gen] Metadata saved to saudi_rs_auto_metadata.json")
    print("[pine-gen] ✅ Done!")

if __name__ == "__main__":
    generate_pine_script()
