"""
Auto-generate TradingView Pine Script with embedded RS data
This script reads the CSV and generates a Pine Script file with RS data embedded as arrays
"""

import pandas as pd
import json
from datetime import datetime

def generate_pine_script(csv_path='saudiexchange_rs_analysis.csv', 
                         output_path='saudi_rs_auto_generated.pine'):
    """
    Generate Pine Script with embedded RS data from CSV
    """
    
    print("[pine-gen] Reading CSV data...")
    df = pd.read_csv(csv_path, encoding='utf-8-sig')
    
    # Sort by Symbol for consistency
    df = df.sort_values('Symbol').reset_index(drop=True)
    
    # Prepare data arrays
    # Ensure symbols are clean strings (remove .0 if interpreted as float)
    symbols = df['Symbol'].astype(str).str.replace(r'\.0$', '', regex=True).tolist()
    companies = df['Company'].tolist()
    rs_values = df['RS'].tolist()
    
    # Generate arrays as Pine Script code
    symbols_array = ', '.join([f'"{s}"' for s in symbols])
    companies_array = ', '.join([f'"{c.replace(chr(34), chr(39))}"' for c in companies])
    rs_array = ', '.join([str(int(r)) for r in rs_values])
    
    total_stocks = len(df)
    last_update = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    # Generate Pine Script
    pine_code = f'''//=============================================================================
// Saudi Market RS Rating - Auto-Generated
// Data Source: https://github.com/ayman368/saudi-market-rs-tracker
// Total Stocks: {total_stocks}
// Last Update: {last_update}
// 
// This script is AUTO-GENERATED by GitHub Actions
// Do NOT edit manually - changes will be overwritten
//=============================================================================

//@version=5
indicator(title='Saudi RS (Auto-Updated)', shorttitle='Saudi RS Auto', overlay=true, max_bars_back = 253)

// ===== EMBEDDED DATA (Auto-Generated) =====
// This data is automatically updated daily from CSV

var string[] SYMBOLS = array.from({symbols_array})
var string[] COMPANIES = array.from({companies_array})
var int[] RS_VALUES = array.from({rs_array})

var int TOTAL_STOCKS = {total_stocks}
var string LAST_UPDATE = "{last_update}"

// ===== CONFIGURATION =====
comparativeTickerId = 'TADAWUL:TASI'

// ===== INPUTS =====
hideRSRat   = input(false, title='Hide Rating', group = 'RS Line')
colorRS     = input(color.rgb(0, 0, 255,0), title = 'Color', group = 'RS Line')
lineTicker  = input('TADAWUL:TASI', title='Comparative Symbol', group = 'Display')
IndexValue  = input(11500, title='Approximate TASI Value', group = 'Display')
offset      = input.int(80, minval = 0, maxval = 2000, title='Offset (%)', group = 'Display')
showTable   = input(true, title='Show RS Table', group = 'Display')

// ===== FIND CURRENT STOCK RS =====
var int currentRS = na
var string currentCompany = ""
var int stockIndex = -1

// Extract symbol from current ticker (e.g., "TADAWUL:1120" → "1120")
currentSymbol = str.tostring(syminfo.ticker)

// Search for current stock in our data
for i = 0 to array.size(SYMBOLS) - 1
    if str.tostring(array.get(SYMBOLS, i)) == currentSymbol
        stockIndex := i
        currentRS := array.get(RS_VALUES, i)
        currentCompany := array.get(COMPANIES, i)
        break

// ===== RS LINE CALCULATION =====
n63  = bar_index < 63  ? bar_index : 63 
n126 = bar_index < 126 ? bar_index : 126
n189 = bar_index < 189 ? bar_index : 189
n252 = bar_index < 252 ? bar_index : 252

comparativeSymbol = request.security(lineTicker, timeframe.period, close)
rsCurve = (close/comparativeSymbol)
rsRatio = timeframe.isweekly ? IndexValue*(offset-10)/100 : IndexValue*offset/100
rs = rsCurve*rsRatio

rsPlot = plot(rs, title='RS Line', style=plot.style_line, linewidth=1, color=colorRS)

// ===== DISPLAY RS LABEL =====
isDaily = timeframe.isdaily
labelText = stockIndex >= 0 ? str.tostring(currentRS) : "N/A"

// Simple label without background
// Shows: "RS Rating: 84" next to the line
label1 = (hideRSRat == false) and barstate.islast and isDaily and stockIndex >= 0 ? 
         label.new(bar_index, rs, text='  RS Rating: ' + labelText, 
                   color = color.new(color.white, 100), // Transparent background
                   size=size.normal, 
                   textcolor=colorRS, // Use the line color for text
                   style=label.style_label_left, 
                   yloc=yloc.price) : na

// Delete previous label
label.delete(label1[1])

// Warning for non-Saudi stocks
if barstate.islast and stockIndex < 0
    label.new(bar_index, high, text='⚠️ Not a Saudi stock', 
              color=color.new(color.white, 100), 
              textcolor=color.red, size=size.small, style=label.style_label_down)

// Warning for non-daily timeframe
if (not isDaily and barstate.islast)
    label.new(bar_index + 10, high, text='Use Daily (1D)', 
              color=color.new(color.white, 100), 
              textcolor=color.orange, size=size.small, style=label.style_label_down)

// ===== INFO =====
// Data updated: {last_update}
// Total stocks: {total_stocks}
// GitHub: https://github.com/ayman368/saudi-market-rs-tracker
'''

    # Save to file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(pine_code)
    
    print(f"[pine-gen] Generated Pine Script: {output_path}")
    print(f"[pine-gen] Total stocks: {total_stocks}")
    print(f"[pine-gen] Last update: {last_update}")
    
    # Also generate a metadata file
    metadata = {
        'total_stocks': total_stocks,
        'last_update': last_update,
        'symbols_count': len(symbols),
        'file_size': len(pine_code),
        'generated_at': datetime.now().isoformat()
    }
    
    with open('saudi_rs_auto_metadata.json', 'w', encoding='utf-8') as f:
        json.dump(metadata, f, indent=2)
    
    print(f"[pine-gen] Metadata saved to saudi_rs_auto_metadata.json")
    print("[pine-gen] ✅ Done!")

if __name__ == "__main__":
    generate_pine_script()
